name: pulumi up (scheduled)
on:
  schedule:
    # run each day at 8am AWST
    - cron: '0 0 * * *'

    # testing (delete)
    - cron: '56 * * * *'

jobs:
  up:
    if: github.event.pull_request.merged == true
    uses: bennettp123/home-stuff/.github/workflows/deploy.yaml@main
    with:
      stack-name: home
      AWS_REGION: ${{ secrets.AWS_REGION }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
