on:
  workflow_call:
    inputs:
      stack-name:
        required: true
        type: string
      pull-request-number:
        required: false
        type: string
      AWS_REGION:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  up:
    concurrency: deploy
    name: pulumi up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: cache .pnpm-store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: install pnpm
        run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
      - run: pnpm install
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ inputs.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: bennettp123/actions@test/fix/comment-on-pr-number-ignored-unless-event-type-is-pullrequest
        with:
          command: up
          stack-name: ${{ inputs.stack-name }}
          cloud-url: s3://home-stuff-bennettp123
          comment-on-pr-number: ${{ inputs.pull-request-number }}
          edit-pr-comment: false
