on:
  workflow_call:
    inputs:
      stack-name:
        required: true
        type: string
      pull-request-number:
        required: false
        type: string
      AWS_REGION:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  PULUMI_SELF_MANAGED_STATE_GZIP: 'true'

jobs:
  up:
    concurrency: deploy
    name: pulumi up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - uses: actions/cache@v3
        name: Set up typescript cache
        with:
          path: ./.tsbuildinfo
          key: ${{ runner.os }}-tsbuildinfo-${{ hashFiles('**/*.ts', '**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-tsbuildinfo-

      - run: pnpm typecheck

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ inputs.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: bennettp123/actions@test/fix/comment-on-pr-number-ignored-unless-event-type-is-pullrequest
        with:
          command: up
          stack-name: ${{ inputs.stack-name }}
          cloud-url: s3://home-stuff-bennettp123
          comment-on-pr-number: ${{ inputs.pull-request-number }}
          edit-pr-comment: false
          color: always
