name: pulumi up
on:
  push:
    branches:
      - main
  schedule:
    # run each day at 8am AWST
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  up:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.event.pull_request.merged == true }}
    steps:
      - uses: jwalton/gh-find-current-pr@v1
        id: pr
        with:
          state: all
      - uses: bennettp123/home-stuff/.github/workflows/deploy.yaml@main
        with:
          stack-name: home
          pull-request-number: ${{ steps.pr.outputs.pr }}
          AWS_REGION: ap-southeast-2
        secrets:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
