name: pulumi up
on:
  push:
    branches:
      - main
  schedule:
    # run each day at 8am AWST
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: jwalton/gh-find-current-pr@v1
        if: ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}
        id: pr
        with:
          state: all
      - name: extract output
        run: |
          if [ '${{ github.event_name }}' = 'schedule' ] || [ '${{ github.event_name }}' = 'workflow_dispatch' ]; then
            echo 'using PR_NUMBER="false" for github.event_name=${{ github.event_name }}'
            PR_NUMBER='false'
          else
            echo 'using PR_NUMBER="${{ steps.pr.outputs.pr }}" for github.event_name=${{ github.event_name }}'
            PR_NUMBER='${{ steps.pr.outputs.pr }}'
          fi
          echo "PR_NUMBER=${PR_NUMBER}" >> "${GITHUB_ENV}"
    outputs:
      pr-number: ${{ env.PR_NUMBER != 'false' && env.PR_NUMBER || false }}

  up:
    needs:
      - get-pr
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.event.pull_request.merged == true || github.event_name == 'push' }}
    # TODO switch back to pulumi/actions@v3
    uses: bennettp123/home-stuff/.github/workflows/deploy.yaml@main
    with:
      stack-name: home
      pull-request-number: ${{ needs.get-pr.outputs.pr-number }}
      AWS_REGION: ap-southeast-2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
