name: pulumi up
on:
  pull_request:
    branches:
      - main
    types:
      - closed
  schedule:
    # run each day at 8am AWST
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  up:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.event.pull_request.merged == true }}
    uses: bennettp123/home-stuff/.github/workflows/deploy.yaml@main
    with:
      stack-name: home
      AWS_REGION: ap-southeast-2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
