name: pulumi up
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  up:
    if: github.event.pull_request.merged == true
    uses: bennettp123/home-stuff/.github/workflows/deploy.yaml@main
    with:
      stack-name: home
      AWS_REGION: ${{ secrets.AWS_REGION }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
