name: pulumi preview

on:
  - pull_request

env:
  PULUMI_SELF_MANAGED_STATE_GZIP: 'true'

jobs:
  preview:
    name: pulumi preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: home
          cloud-url: s3://home-stuff-bennettp123
          comment-on-pr: true
          edit-pr-comment: false
          color: always
